### ISSUE TITLE
cannot access org.tinystruct.AbstractApplication

### ISSUE THREAD

**Issue by TuJinkai** [tinystruct/smalltalk#2]
An error occurred when I was using maven to build this project：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project smalltalk: Compilation failure
[ERROR] /root/smalltalk/src/main/java/custom/application/lock.java:[3,22] cannot access org.tinystruct.AbstractApplication
[ERROR]   bad class file: /root/.m2/repository/org/tinystruct/tinystruct/0.9.3/tinystruct-0.9.3-jar-with-dependencies.jar(org/tinystruct/AbstractApplication.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

I don't kown what means：cannot access org.tinystruct.AbstractApplication

how can i do？

**Comment by ww241119786** [comment]
Same problem...

**Comment by m0ver** [comment]
That means your JDK version is not match to the library, please install OpenJDK 11+.  The issue will be resolved automatically.

**Comment by ww241119786** [comment]
> That means your JDK version is not match to the library, please install OpenJDK 11+. The issue will be resolved automatically.

thank! problem solved!

**Comment by m0ver** [comment]
Great! I'll close the ticket. Any issues please feel free to raise up a new. Thanks!

**Comment by TuJinkai** [comment]
thanks ! It's useful
