### ISSUE TITLE
deploy with a domain name still post to localhost:777

### ISSUE THREAD

**Issue by C217355** [tinystruct/smalltalk#4]
I am deploying it to a server with docker, it works fine in local machine with docker.
after deploy to server, and after using nginx to transfer the request with https://xxx/smalltalk, it doesn't run properly.

1. found some links in smalltalk.view that starts with absolute path "/scripts/....", changed to "./scripts/..."

after that, build docker and run in server, found ajax request still posting to http://localhost:777
I am not very family with java, so not found how %LINK works.

it is better we can fix this :)

**Comment by m0ver** [comment]
you need to set request header for host name in nginx then should be fine.

**Comment by m0ver** [comment]
I’ll close the ticket as it's an issue from the project itself.
